language: bash
addons:
  ssh_known_hosts:
  - weer.nielsvanderveer.nl

before_install:
- openssl aes-256-cbc -K $encrypted_c5a38b52ab1f_key -iv $encrypted_c5a38b52ab1f_iv
  -in .travis/deploy_rsa.enc -out deploy_rsa -d

branches:
  only:
  - master

deploy:
  provider: script
  skip_cleanup: true
  script: bash .travis/deploy.sh
  on:
    branch: master
